export const CANONICAL_COUNTRIES: string[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const ISO_4217_CURRENCIES: string[] = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'FOK',
  'GBP',
  'GEL',
  'GGP',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'IMP',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JEP',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLE',
  'SLL',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TVD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XDR',
  'XOF',
  'XPF',
  'YER',
  'ZAR',
  'ZMW',
  'ZWL',
];

export const COUNTRY_CURRENCY_DEFAULT_MAP: Record<string, string> = {
  Afghanistan: 'AFN',
  Albania: 'ALL',
  Algeria: 'DZD',
  Andorra: 'EUR',
  Angola: 'AOA',
  'Antigua and Barbuda': 'XCD',
  Argentina: 'ARS',
  Armenia: 'AMD',
  Australia: 'AUD',
  Austria: 'EUR',
  Azerbaijan: 'AZN',
  Bahamas: 'BSD',
  Bahrain: 'BHD',
  Bangladesh: 'BDT',
  Barbados: 'BBD',
  Belarus: 'BYN',
  Belgium: 'EUR',
  Belize: 'BZD',
  Benin: 'XOF',
  Bhutan: 'BTN',
  Bolivia: 'BOB',
  'Bosnia and Herzegovina': 'BAM',
  Botswana: 'BWP',
  Brazil: 'BRL',
  Brunei: 'BND',
  Bulgaria: 'BGN',
  'Burkina Faso': 'XOF',
  Burundi: 'BIF',
  'Cabo Verde': 'CVE',
  Cambodia: 'KHR',
  Cameroon: 'XAF',
  Canada: 'CAD',
  'Central African Republic': 'XAF',
  Chad: 'XAF',
  Chile: 'CLP',
  China: 'CNY',
  Colombia: 'COP',
  Comoros: 'KMF',
  Congo: 'XAF',
  'Costa Rica': 'CRC',
  Croatia: 'EUR',
  Cuba: 'CUP',
  Cyprus: 'EUR',
  'Czech Republic': 'CZK',
  Denmark: 'DKK',
  Djibouti: 'DJF',
  Dominica: 'XCD',
  'Dominican Republic': 'DOP',
  'East Timor': 'USD',
  Ecuador: 'USD',
  Egypt: 'EGP',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'XAF',
  Eritrea: 'ERN',
  Estonia: 'EUR',
  Eswatini: 'SZL',
  Ethiopia: 'ETB',
  Fiji: 'FJD',
  Finland: 'EUR',
  France: 'EUR',
  Gabon: 'XAF',
  Gambia: 'GMD',
  Georgia: 'GEL',
  Germany: 'EUR',
  Ghana: 'GHS',
  Greece: 'EUR',
  Grenada: 'XCD',
  Guatemala: 'GTQ',
  Guinea: 'GNF',
  'Guinea-Bissau': 'XOF',
  Guyana: 'GYD',
  Haiti: 'HTG',
  Honduras: 'HNL',
  Hungary: 'HUF',
  Iceland: 'ISK',
  India: 'INR',
  Indonesia: 'IDR',
  Iran: 'IRR',
  Iraq: 'IQD',
  Ireland: 'EUR',
  Israel: 'ILS',
  Italy: 'EUR',
  'Ivory Coast': 'XOF',
  Jamaica: 'JMD',
  Japan: 'JPY',
  Jordan: 'JOD',
  Kazakhstan: 'KZT',
  Kenya: 'KES',
  Kiribati: 'AUD',
  Kosovo: 'EUR',
  Kuwait: 'KWD',
  Kyrgyzstan: 'KGS',
  Laos: 'LAK',
  Latvia: 'EUR',
  Lebanon: 'LBP',
  Lesotho: 'LSL',
  Liberia: 'LRD',
  Libya: 'LYD',
  Liechtenstein: 'CHF',
  Lithuania: 'EUR',
  Luxembourg: 'EUR',
  Madagascar: 'MGA',
  Malawi: 'MWK',
  Malaysia: 'MYR',
  Maldives: 'MVR',
  Mali: 'XOF',
  Malta: 'EUR',
  'Marshall Islands': 'USD',
  Mauritania: 'MRU',
  Mauritius: 'MUR',
  Mexico: 'MXN',
  Micronesia: 'USD',
  Moldova: 'MDL',
  Monaco: 'EUR',
  Mongolia: 'MNT',
  Montenegro: 'EUR',
  Morocco: 'MAD',
  Mozambique: 'MZN',
  Myanmar: 'MMK',
  Namibia: 'NAD',
  Nauru: 'AUD',
  Nepal: 'NPR',
  Netherlands: 'EUR',
  'New Zealand': 'NZD',
  Nicaragua: 'NIO',
  Niger: 'XOF',
  Nigeria: 'NGN',
  'North Korea': 'KPW',
  'North Macedonia': 'MKD',
  Norway: 'NOK',
  Oman: 'OMR',
  Pakistan: 'PKR',
  Palau: 'USD',
  Palestine: 'ILS',
  Panama: 'PAB',
  'Papua New Guinea': 'PGK',
  Paraguay: 'PYG',
  Peru: 'PEN',
  Philippines: 'PHP',
  Poland: 'PLN',
  Portugal: 'EUR',
  Qatar: 'QAR',
  Romania: 'RON',
  Russia: 'RUB',
  Rwanda: 'RWF',
  'Saint Kitts and Nevis': 'XCD',
  'Saint Lucia': 'XCD',
  'Saint Vincent and the Grenadines': 'XCD',
  Samoa: 'WST',
  'San Marino': 'EUR',
  'Sao Tome and Principe': 'STN',
  'Saudi Arabia': 'SAR',
  Senegal: 'XOF',
  Serbia: 'RSD',
  Seychelles: 'SCR',
  'Sierra Leone': 'SLE',
  Singapore: 'SGD',
  Slovakia: 'EUR',
  Slovenia: 'EUR',
  'Solomon Islands': 'SBD',
  Somalia: 'SOS',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  'South Sudan': 'SSP',
  Spain: 'EUR',
  'Sri Lanka': 'LKR',
  Sudan: 'SDG',
  Suriname: 'SRD',
  Sweden: 'SEK',
  Switzerland: 'CHF',
  Syria: 'SYP',
  Taiwan: 'TWD',
  Tajikistan: 'TJS',
  Tanzania: 'TZS',
  Thailand: 'THB',
  Togo: 'XOF',
  Tonga: 'TOP',
  'Trinidad and Tobago': 'TTD',
  Tunisia: 'TND',
  Turkey: 'TRY',
  Turkmenistan: 'TMT',
  Tuvalu: 'AUD',
  Uganda: 'UGX',
  Ukraine: 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  Uruguay: 'UYU',
  Uzbekistan: 'UZS',
  Vanuatu: 'VUV',
  'Vatican City': 'EUR',
  Venezuela: 'VES',
  Vietnam: 'VND',
  Yemen: 'YER',
  Zambia: 'ZMW',
  Zimbabwe: 'ZWL',
};
